// <auto-generated />
// Este arquivo é gerado automaticamente pelo Entity Framework Core (EF Core)
// quando uma migração é adicionada. Não deve ser modificado manualmente.
// Ele contém um "snapshot" do modelo de dados em um determinado ponto no tempo,
// usado pelo EF Core para detectar mudanças no esquema do banco de dados
// e gerar as próximas migrações.

using System;
using Api.Data; // Importa o namespace onde o AppDataContext está definido.
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    // A anotação DbContext indica a qual contexto de banco de dados esta migração pertence.
    [DbContext(typeof(AppDataContext))]
    // O atributo Migration associa esta classe à migração específica pelo seu timestamp.
    [Migration("20250615233656_InitialCompleteSchema")]
    partial class InitialCompleteSchema
    {
        /// <inheritdoc />
        // Este método é chamado pelo EF Core para construir o modelo de dados para esta migração.
        // Ele define a estrutura das tabelas, suas colunas, chaves primárias, chaves estrangeiras e relacionamentos.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Desabilita avisos de obsolescência para garantir compatibilidade com versões mais antigas do EF Core,
            // especialmente útil em migrações geradas automaticamente.

            // Define a versão do produto Entity Framework Core utilizada.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // Configuração da entidade 'Aluno'.
            modelBuilder.Entity("Api.Models.Aluno", b =>
                {
                    // Define 'Id' como chave primária e que ela será gerada automaticamente pelo banco de dados (IDENTITY para INTEGER).
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER"); // Tipo de coluna no SQLite.

                    // Configuração da propriedade 'DataNascimento'.
                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT"); // Armazenado como TEXT no SQLite para DateTime.

                    // Configuração da propriedade 'Email': obrigatória (IsRequired) e com limite de 100 caracteres (HasMaxLength).
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Configuração da propriedade 'Matricula': obrigatória e com limite de 20 caracteres.
                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    // Configuração da propriedade 'Nome': obrigatória e com limite de 100 caracteres.
                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Define 'Id' como a chave primária da tabela 'Alunos'.
                    b.HasKey("Id");

                    // Mapeia a entidade 'Aluno' para a tabela 'Alunos'.
                    b.ToTable("Alunos");
                });

            // Configuração da entidade 'Curso'.
            modelBuilder.Entity("Curso", b =>
                {
                    // Define 'Id' como chave primária e que ela será gerada automaticamente.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Configuração da propriedade 'Nome': obrigatória e com limite de 100 caracteres.
                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Define 'Id' como a chave primária da tabela 'Cursos'.
                    b.HasKey("Id");

                    // Mapeia a entidade 'Curso' para a tabela 'Cursos'.
                    b.ToTable("Cursos");
                });

            // Configuração da entidade 'Materia'.
            modelBuilder.Entity("Materia", b =>
                {
                    // Define 'Id' como chave primária e que ela será gerada automaticamente.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Configuração da chave estrangeira 'CursoId': obrigatória.
                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    // Configuração da propriedade 'Nome': obrigatória e com limite de 100 caracteres.
                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Define 'Id' como a chave primária da tabela 'Materias'.
                    b.HasKey("Id");

                    // Cria um índice na coluna 'CursoId' para otimizar buscas e garantir a integridade referencial.
                    b.HasIndex("CursoId");

                    // Mapeia a entidade 'Materia' para a tabela 'Materias'.
                    b.ToTable("Materias");
                });

            // Configuração do relacionamento entre 'Materia' e 'Curso'.
            modelBuilder.Entity("Materia", b =>
                {
                    // Define que 'Materia' tem um relacionamento de "um para muitos" com 'Curso'.
                    // 'Materia' possui uma propriedade de navegação 'Curso'.
                    b.HasOne("Curso", "Curso")
                        // 'Curso' possui uma coleção de 'Materias'.
                        .WithMany("Materias")
                        // Define 'CursoId' como a chave estrangeira na tabela 'Materias'.
                        .HasForeignKey("CursoId")
                        // Comportamento de exclusão em cascata: se um Curso for excluído, todas as Materias associadas também serão.
                        .OnDelete(DeleteBehavior.Cascade)
                        // A chave estrangeira 'CursoId' é obrigatória.
                        .IsRequired();

                    // Configura a navegação para a propriedade 'Curso' na entidade 'Materia'.
                    b.Navigation("Curso");
                });

            // Configuração da propriedade de navegação 'Materias' na entidade 'Curso'.
            modelBuilder.Entity("Curso", b =>
                {
                    // Permite a navegação da entidade 'Curso' para suas 'Materias' associadas.
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}