// <auto-generated />
// Este arquivo é gerado automaticamente pelo Entity Framework Core (EF Core)
// e representa o "snapshot" mais recente do modelo de dados do seu DbContext.
// Ele é usado para comparação e detecção de mudanças no esquema do banco de dados
// quando novas migrações são adicionadas. Não deve ser editado manualmente.

using System;
using Api.Data; // Importa o namespace onde o AppDataContext está definido.
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    // A anotação DbContext indica a qual contexto de banco de dados este snapshot pertence.
    [DbContext(typeof(AppDataContext))]
    // Esta classe herda de ModelSnapshot, que é a base para os snapshots de modelo do EF Core.
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        // O método BuildModel é invocado pelo EF Core para reconstruir o modelo de dados completo
        // a partir do snapshot. Ele espelha as configurações do seu DbContext.OnModelCreating
        // e as migrações aplicadas.
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Desabilita avisos de obsolescência para garantir compatibilidade e permitir o código gerado.

            // Define a versão do produto Entity Framework Core utilizada no momento da geração do snapshot.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // Configuração da entidade 'Aluno'.
            modelBuilder.Entity("Api.Models.Aluno", b =>
                {
                    // Propriedade 'Id' configurada como chave primária com geração de valor automática (ValueGeneratedOnAdd)
                    // e mapeada para o tipo INTEGER no SQLite.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Propriedade 'DataNascimento' mapeada para o tipo TEXT no SQLite para armazenar datas.
                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    // Propriedade 'Email' configurada como obrigatória (IsRequired),
                    // com comprimento máximo de 100 caracteres (HasMaxLength) e mapeada para TEXT.
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Propriedade 'Matricula' configurada como obrigatória,
                    // com comprimento máximo de 20 caracteres e mapeada para TEXT.
                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    // Propriedade 'Nome' configurada como obrigatória,
                    // com comprimento máximo de 100 caracteres e mapeada para TEXT.
                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Define 'Id' como a chave primária da entidade 'Aluno'.
                    b.HasKey("Id");

                    // Mapeia a entidade 'Aluno' para a tabela 'Alunos' no banco de dados.
                    b.ToTable("Alunos");
                });

            // Configuração da entidade 'Curso'.
            modelBuilder.Entity("Curso", b =>
                {
                    // Propriedade 'Id' configurada como chave primária com geração de valor automática
                    // e mapeada para o tipo INTEGER.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Propriedade 'Nome' configurada como obrigatória,
                    // com comprimento máximo de 100 caracteres e mapeada para TEXT.
                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Define 'Id' como a chave primária da entidade 'Curso'.
                    b.HasKey("Id");

                    // Mapeia a entidade 'Curso' para a tabela 'Cursos' no banco de dados.
                    b.ToTable("Cursos");
                });

            // Configuração da entidade 'Materia'.
            modelBuilder.Entity("Materia", b =>
                {
                    // Propriedade 'Id' configurada como chave primária com geração de valor automática
                    // e mapeada para o tipo INTEGER.
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    // Propriedade 'CursoId' (chave estrangeira) mapeada para o tipo INTEGER.
                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    // Propriedade 'Nome' configurada como obrigatória,
                    // com comprimento máximo de 100 caracteres e mapeada para TEXT.
                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    // Define 'Id' como a chave primária da entidade 'Materia'.
                    b.HasKey("Id");

                    // Cria um índice na coluna 'CursoId' para otimização de consultas e integridade.
                    b.HasIndex("CursoId");

                    // Mapeia a entidade 'Materia' para a tabela 'Materias' no banco de dados.
                    b.ToTable("Materias");
                });

            // Configuração do relacionamento entre 'Materia' e 'Curso'.
            modelBuilder.Entity("Materia", b =>
                {
                    // Define o relacionamento de "um para muitos" (uma Materia pertence a um Curso).
                    // Configura a chave estrangeira 'CursoId' e o comportamento de exclusão em cascata.
                    b.HasOne("Curso", "Curso")
                        .WithMany("Materias")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade) // Se um Curso for deletado, suas Materias também serão.
                        .IsRequired(); // 'CursoId' é obrigatório.

                    // Permite a navegação da entidade 'Materia' para o seu 'Curso' associado.
                    b.Navigation("Curso");
                });

            // Configuração da propriedade de navegação de 'Curso' para 'Materias'.
            modelBuilder.Entity("Curso", b =>
                {
                    // Permite a navegação da entidade 'Curso' para sua coleção de 'Materias'.
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}